app:
    resource: "@AppBundle/Controller/"
    type:     annotation

contact:
    path:     /contact2
    defaults: { _controller: AppBundle:Blog:firefoxContact }
    condition: "context.getMethod() in ['GET', 'HEAD'] and request.headers.get('User-Agent') matches '/firefox/i'"

_welcome:
    path:     /
    defaults: { _controller: AppBundle:Hello:index }

article_show:
    path:     /article/{slug}
    defaults: { _controller: AppBundle:Article:show }